protectedFiles = [
  "board.3drag.h",
  "board.gen3.h",
  "board.gen6.h",
  "board.gen7-v1.1-v1.3.h",
  "board.gen7-v1.4.h",
  "board.ramps-v1.2.h",
  "board.ramps-v1.3.h",
  "board.rumba.h",
  "board.sanguinololu-v1.1.h",
  "board.sanguinololu-v1.2.h",
  "board.sanguish.h",
  "board.teensy.h",
  "board.teensypp.h",
  "printer.mendel.h",
  "printer.wolfstrap.h",
  ]
